### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by xlnwel** [ppwwyyxx/dash-docset-tensorflow#4]
Hi, I ran into an error: 
`Connecting to www.tensorflow.org|74.125.23.139|:443... failed: Operation timed out.`
when I executed 
`wget -nc -np --compression=gzip --domains=www.tensorflow.org -e robots=off --adjust-extension -r 'https://www.tensorflow.org/versions/master/api_docs/'`
I omitted `-N` since I received an error message: 
`Can't timestamp and not clobber old files at the same time.
Usage: wget [OPTION]... [URL]...`
When using it

**Comment by ppwwyyxx** [comment]
Thanks for the note. The command line was fixed.

Getting connection time out is your own network problem.

**Comment by xlnwel** [comment]
Maybe, but I've tried to use VPN, still the same result. Anyway, I've downloaded tgz file, and it works fine. Thanks for your work :)
